server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/springbokdev/config-repo.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
