server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/springbokdev/config-repo.git
          #searchPaths: service_a, service_b, service_c

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka