#
#   This is the core configuration for a configuration service. 
#

server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/springbokdev/config-repo/
          #searchPaths: service_a, service_b
